version: "3"

services:
    webserver:
        build:
            context: ./docker/php
        container_name: "${COMPOSE_PROJECT_NAME}-php"
        restart: "always"
        ports:
            - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
            - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
        links:
            - database
        volumes:
            - .:/var/www/html:rw
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/ssl:/etc/apache2/ssl/
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - ./docker/logs/apache2:/var/log/apache2
            - ./docker/logs/xdebug:/var/log/xdebug
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
            PMA_PORT: ${HOST_MACHINE_PMA_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
            XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    database:
        build:
            context: "./docker/mysql"
        container_name: "${COMPOSE_PROJECT_NAME}-database"
        restart: "always"
        ports:
            - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
        volumes:
            - ./docker/initdb:/docker-entrypoint-initdb.d
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin
        container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            UPLOAD_LIMIT: ${UPLOAD_LIMIT}
            MEMORY_LIMIT: ${MEMORY_LIMIT}
        ports:
            - "${HOST_MACHINE_PMA_PORT}:80"
            - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
        volumes:
            - /sessions
            - ${PHP_INI-./docker/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini