name: Deploy documentation to Github Pages
on:
  push:
    branches:
      - "release"
      - "initial-docs-setup"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build documentation
        uses: Tiryoh/actions-mkdocs@v0
        with:
          configfile: "documentation/mkdocs.yml"

      - name: Debug paths
        shell: bash
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory: $(ls)"
          echo "Contents of site directory: $(ls site)"
          echo "Contents of documentation directory: $(ls documentation)"

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: documentation
          FOLDER: ./site
