name: Deploy documentation to Github Pages
on:
  push:
    branches:
      - "release"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build documentation
        uses: Tiryoh/actions-mkdocs@v0
        with:
          configfile: "documentation/mkdocs.yml"

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: documentation
          FOLDER: ./documentation/site
